// Generated by CoffeeScript 1.3.3
var app, request, should;

require('../utils');

request = require('supertest');

app = require('../..').app;

should = require('should');

describe('User: api', function() {
  var baseUrl, user1;
  baseUrl = '/-/api/v1/users';
  user1 = {
    id: '',
    name: {
      givenName: 'Micheal',
      middleName: '"Danger"',
      familyName: 'Scorn'
    },
    emails: {
      value: 'scorn@example.com'
    },
    username: 'agentscorn'
  };
  describe('POST /-/api/v1/users', function() {
    return it('should create a new user if request is valid', function(done) {
      return request(app).post(baseUrl).send(user1).set('Accept', 'application/json').expect(201).end(function(err, res) {
        var u;
        u = JSON.parse(res.text);
        should.not.exist(err);
        should.exist(u.id);
        u.name.givenName.should.equal('Micheal');
        u.name.middleName.should.equal('"Danger"');
        u.name.familyName.should.equal('Scorn');
        u.username.should.equal('agentscorn');
        return done();
      });
    });
  });
  return describe('GET /-/api/v1/users', function() {
    var userId;
    userId = void 0;
    beforeEach(function(done) {
      return request(app).post(baseUrl).send(user1).expect(201).end(function(err, res) {
        var u;
        u = JSON.parse(res.text);
        userId = u.id;
        should.not.exist(err);
        return done();
      });
    });
    return it('should return a new user if it exists', function(done) {
      return request(app).get(baseUrl + '/' + userId).expect(200).end(function(err, res) {
        var u;
        u = JSON.parse(res.text);
        should.not.exist(err);
        u.name.givenName.should.equal('Micheal');
        u.name.middleName.should.equal('"Danger"');
        u.name.familyName.should.equal('Scorn');
        u.username.should.equal('agentscorn');
        return done();
      });
    });
  });
});
