// Generated by CoffeeScript 1.3.3
var app, request, should;

require('../utils');

request = require('supertest');

app = require('../..').app;

should = require('should');

describe('Accounts: API', function() {
  var baseUrl;
  baseUrl = '/-/api/v1/account/providers';
  return describe('GET /-/api/v1/account/providers', function() {
    return it('should return a 401 error if the user is not authenticated', function(done) {
      return request(app).get(baseUrl).set('Accept', 'application/json').expect(401).end(function(err, res) {
        should.not.exist(err);
        res.text.should.equal('Unauthorized');
        return done();
      });
    });
  });
});
