// Generated by CoffeeScript 1.3.3
var app, request, should;

require('../../utils');

request = require('supertest');

app = require('../../..').app;

should = require('should');

describe('Password: API', function() {
  var baseUrl;
  baseUrl = '/-/api/v1/auth/password';
  describe('GET /-/api/v1/auth/password', function() {
    return it('should return a 401 error if the user is not authenticated', function(done) {
      return request(app).get(baseUrl).set('Accept', 'application/json').expect(401).end(function(err, res) {
        should.not.exist(err);
        res.text.should.equal('Unauthorized');
        return done();
      });
    });
  });
  return describe('POST /-/api/v1/auth/password', function() {
    it('should return a 400 error if password is empty', function(done) {
      var obj1;
      obj1 = {
        password: '',
        user: {
          name: {
            givenName: 'Micheal',
            familyName: 'Scorn'
          },
          email: 'scorn@example.com',
          username: 'agentscorn'
        }
      };
      return request(app).post(baseUrl).send(obj1).set('Accept', 'application/json').expect(400).end(function(err, res) {
        var r;
        should.not.exist(err);
        r = JSON.parse(res.text);
        r.code.should.equal(12);
        r.message.should.equal('invalid password length');
        return done();
      });
    });
    return it('should create a new user and return a 201 if valid', function(done) {
      var obj1;
      obj1 = {
        password: 'pass1',
        user: {
          id: '',
          name: {
            givenName: 'Micheal',
            familyName: 'Scorn'
          },
          email: 'SCORN@example.com'
        }
      };
      return request(app).post(baseUrl).send(obj1).set('Accept', 'application/json').expect(201).end(function(err, res) {
        var u;
        should.not.exist(err);
        u = JSON.parse(res.text);
        should.exist(u.id);
        u.name.givenName.should.equal('Micheal');
        u.name.familyName.should.equal('Scorn');
        u.emails[0].value.should.equal('scorn@example.com');
        return done();
      });
    });
  });
});
