// Generated by CoffeeScript 1.3.3
var Password, should;

require('../../utils');

should = require('should');

Password = require('../../../auth/password/model').Password;

describe('Password', function() {
  var userId;
  userId = '000000000000000000000001';
  describe('#new()', function() {
    it('should create a new password entity when the info is vaild', function(done) {
      return Password["new"](userId, 'pass1', function(err, p) {
        should.not.exist(err);
        should.exist(p._id);
        should.exist(p.createdAt);
        should.exist(p.auth.passwordHash);
        String(p.userId).should.equal(userId);
        p.provider.name.should.equal('local');
        return Password.findOne({
          userId: userId
        }, function(err, u) {
          String(p.userId).should.equal(userId);
          return done();
        });
      });
    });
    it('should return an error when the password is to short', function(done) {
      return Password["new"](userId, 'pas', function(err, p) {
        should.exist(err);
        err.code.should.equal(12);
        err.message.should.equal('invalid password length');
        should.not.exist(p);
        return done();
      });
    });
    return it('should return an error if the user has already created a password', function(done) {
      return Password["new"](userId, 'pass1', function(err, p) {
        should.not.exist(err);
        return Password["new"](userId, 'pass1', function(err, p) {
          err.code.should.equal(11000);
          should.exist(err);
          return done();
        });
      });
    });
  });
  return describe('#authenticate()', function() {
    var pass;
    pass = 'pass1';
    beforeEach(function(done) {
      return Password["new"](userId, pass, function(err, p) {
        return done();
      });
    });
    it('should return true when password is vaild', function(done) {
      return Password.authenticate(userId, pass, function(err, valid) {
        should.not.exist(err);
        valid.should.equal(true);
        return done();
      });
    });
    return it('should return false when password is invaild', function(done) {
      return Password.authenticate(userId, 'fake', function(err, valid) {
        should.not.exist(err);
        valid.should.equal(false);
        return done();
      });
    });
  });
});
