// Generated by CoffeeScript 1.3.3
var app, mongoose, request, should;

require('../../utils');

request = require('supertest');

app = require('../../..').app;

should = require('should');

mongoose = require('mongoose');

describe('Password', function() {
  var authUrl;
  authUrl = '/-/auth';
  return describe('POST /-/auth/password', function() {
    return it('create user and redirect to "/login"', function(done) {
      return request(app).post(authUrl + '/password').send({
        username: 'test@exampl.com',
        password: 'pass1'
      }).expect(200).end(function(err, res) {
        return done();
      });
    });
  });
});
