// Generated by CoffeeScript 1.3.3
var AuthProfile, should;

require('../utils');

should = require('should');

AuthProfile = require('../../auth/model').AuthProfile;

describe('AuthProfile', function() {
  var profile, userId;
  userId = '000000000000000000000001';
  profile = {
    name: {
      givenName: 'Bob',
      familyName: 'Dole'
    }
  };
  describe('#new()', function() {
    return it('should create a new auth entity when the info is vaild', function(done) {
      return AuthProfile["new"]('local', userId, userId, profile, function(err, a) {
        should.not.exist(err);
        should.exist(a._id);
        should.exist(a.createdAt);
        a.profile.provider.should.equal('local');
        a.profile.id.should.equal(userId);
        String(a.userId).should.equal(userId);
        return AuthProfile.findOne({
          userId: userId
        }, function(err, u) {
          String(a.userId).should.equal(userId);
          return done();
        });
      });
    });
  });
  return describe('#get()', function() {
    beforeEach(function(done) {
      return AuthProfile["new"]('local', userId, userId, profile, function(err, a) {
        return done();
      });
    });
    return it('should get an auth entity by provider and id', function(done) {
      return AuthProfile.get('local', userId, function(err, a) {
        should.not.exist(err);
        String(a.userId).should.equal(userId);
        a.profile.provider.should.equal('local');
        a.profile.id.should.equal(userId);
        return done();
      });
    });
  });
});
